import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useCompose } from '../context/ComposeContext';
import { 
  Building, 
  Mail, 
  ExternalLink, 
  Sparkles, 
  BookOpen, 
  Plus, 
  Send, 
  RotateCw, 
  Copy, 
  Check, 
  ArrowLeft,
  Calendar,
  Save,
  Trash2,
  X
} from 'lucide-react';
import api from '../services/api';
import toast from 'react-hot-toast';
import { formatErrorMessage } from '../utils/errorUtils';

const ProfessorDetailPage = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { openCompose } = useCompose();

  const [prof, setProf] = useState(null);
  const [loading, setLoading] = useState(true);
  const [analyzing, setAnalyzing] = useState(false);
  const [copied, setCopied] = useState(false);

  // In-page composer state
  const [subject, setSubject] = useState('');
  const [body, setBody] = useState('');
  const [tone, setTone] = useState('Formal Academic');
  const [wordCount, setWordCount] = useState(250);
  const [drafting, setDrafting] = useState(false);

  // Add paper modal
  const [showPaperModal, setShowPaperModal] = useState(false);
  const [newPaper, setNewPaper] = useState({ title: '', year: 2024, venue: '', abstract: '', doi_or_url: '' });

  const fetchProfessor = async () => {
    try {
      const res = await api.get(`/professors/${id}`);
      setProf(res.data);
    } catch (err) {
      console.error(err);
      toast.error("Failed to load professor dossier.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchProfessor();
  }, [id]);

  const handleRunReview = async () => {
    setAnalyzing(true);
    try {
      const res = await api.post('/ai/review', { professor_id: parseInt(id) });
      toast.success(`Gemini Research Review Complete! Match: ${res.data.match_score}/10`);
      fetchProfessor();
    } catch (err) {
      console.error(err);
      toast.error("AI review failed.");
    } finally {
      setAnalyzing(false);
    }
  };

  const handleGenerateDraft = async () => {
    setDrafting(true);
    try {
      const res = await api.post('/ai/draft-email', {
        professor_id: parseInt(id),
        tone,
        word_count: wordCount
      });
      setSubject(res.data.subject);
      setBody(res.data.body);
      toast.success("Academic Cold Email generated by Gemini!");
    } catch (err) {
      console.error(err);
      toast.error("Email draft generation failed.");
    } finally {
      setDrafting(false);
    }
  };

  const handleGenerateFollowUp = async () => {
    setDrafting(true);
    try {
      const res = await api.post('/ai/follow-up', {
        professor_id: parseInt(id),
        follow_up_stage: 1
      });
      setSubject(res.data.subject);
      setBody(res.data.body);
      toast.success("Follow-up email generated by Gemini!");
    } catch (err) {
      toast.error("Failed to generate follow-up.");
    } finally {
      setDrafting(false);
    }
  };

  const handleCopyForGmail = () => {
    if (!body) {
      toast.error("Draft is empty.");
      return;
    }
    const fullText = `Subject: ${subject}\n\n${body}`;
    navigator.clipboard.writeText(fullText);
    setCopied(true);
    toast.success("Copied to clipboard! Ready to paste into Gmail.", { icon: '📋' });
    setTimeout(() => setCopied(false), 3000);
  };

  const handleSaveDraft = async () => {
    if (!subject || !body) {
      toast.error("Please provide both subject and body.");
      return;
    }
    try {
      await api.post('/emails', {
        professor_id: parseInt(id),
        subject,
        body
      });
      toast.success("Draft saved to CRM!");
      fetchProfessor();
    } catch (err) {
      toast.error("Failed to save draft.");
    }
  };

  const handleSendNow = async () => {
    if (!subject || !body) {
      toast.error("Please provide both subject and body.");
      return;
    }
    try {
      const draftRes = await api.post('/emails', {
        professor_id: parseInt(id),
        subject,
        body
      });
      const draftId = draftRes.data.id;

      const sendRes = await api.post('/emails/send', {
        draft_id: draftId,
        send_now: true
      });
      toast.success(sendRes.data.message || "Email dispatched!");
      fetchProfessor();
    } catch (err) {
      console.error(err);
      toast.error(formatErrorMessage(err, "Dispatch failed. (You can also copy to Gmail directly)."));
    }
  };

  const handleAddPaper = async (e) => {
    e.preventDefault();
    try {
      await api.post(`/professors/${id}/papers`, newPaper);
      toast.success("Paper added to dossier!");
      setShowPaperModal(false);
      setNewPaper({ title: '', year: 2024, venue: '', abstract: '', doi_or_url: '' });
      fetchProfessor();
    } catch (err) {
      toast.error("Failed to add paper.");
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
      </div>
    );
  }

  if (!prof) return <div>Professor not found.</div>;

  return (
    <div className="space-y-6">
      {/* Top Header Card */}
      <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-2xs flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate('/professors')}
            className="p-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-600 transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
          </button>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-xl font-bold text-slate-900">{prof.name}</h2>
              <span className="text-xs px-2.5 py-0.5 rounded-full font-bold bg-blue-100 text-blue-800 border border-blue-200">
                {prof.status}
              </span>
            </div>
            <div className="text-xs text-slate-600 flex items-center gap-2 mt-0.5 font-medium">
              <Building className="w-3.5 h-3.5 text-slate-400" />
              <span className="text-blue-900 font-bold">{prof.institution}</span>
              {prof.department && <span>• {prof.department}</span>}
              <span className="text-slate-500">• {prof.email}</span>
            </div>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {prof.homepage_url && (
            <a
              href={prof.homepage_url}
              target="_blank"
              rel="noreferrer"
              className="px-3 py-1.5 rounded-xl border border-slate-200 text-xs font-semibold text-slate-700 hover:bg-slate-50 flex items-center gap-1.5 shadow-2xs"
            >
              <ExternalLink className="w-3.5 h-3.5 text-slate-500" />
              <span>Lab Webpage</span>
            </a>
          )}
          <button
            onClick={handleRunReview}
            disabled={analyzing}
            className="px-3.5 py-1.5 rounded-xl bg-indigo-50 hover:bg-indigo-100 border border-indigo-200 text-indigo-700 text-xs font-bold shadow-2xs flex items-center gap-1.5 transition-all disabled:opacity-50"
          >
            <Sparkles className="w-3.5 h-3.5 text-indigo-600" />
            <span>{analyzing ? "Synthesizing..." : "Run AI Review"}</span>
          </button>
          <button
            onClick={() => openCompose({
              professorId: prof.id,
              professorName: prof.name,
              institution: prof.institution,
              recipientEmail: prof.email,
              mode: 'follow_up',
              followUpStage: 1
            })}
            className="px-3.5 py-1.5 rounded-xl bg-amber-50 hover:bg-amber-100 border border-amber-200 text-amber-800 text-xs font-bold shadow-2xs flex items-center gap-1.5 transition-all"
          >
            <RotateCw className="w-3.5 h-3.5 text-amber-600" />
            <span>Take Follow-Up</span>
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-5">
        {/* Left Column: Papers & Gemini Synthesis (5 cols) */}
        <div className="lg:col-span-5 space-y-5">
          {/* AI Review Deck */}
          <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-2xs">
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-sm font-bold text-slate-900 flex items-center gap-1.5">
                <Sparkles className="w-4 h-4 text-indigo-600" />
                <span>Gemini Research Review & Gaps</span>
              </h3>
              {prof.match_score > 0 && (
                <span className="text-xs font-extrabold px-2.5 py-1 rounded-full bg-emerald-100 text-emerald-800 border border-emerald-200">
                  {prof.match_score} / 10 Match
                </span>
              )}
            </div>

            {prof.ai_synthesis ? (
              <div className="text-xs text-slate-700 leading-relaxed whitespace-pre-wrap bg-slate-50 p-3.5 rounded-xl max-h-72 overflow-y-auto font-mono text-[11px] border border-slate-200">
                {prof.ai_synthesis}
              </div>
            ) : (
              <div className="text-center py-8 text-xs text-slate-400 bg-slate-50 rounded-xl border border-dashed border-slate-200">
                <Sparkles className="w-6 h-6 mx-auto text-indigo-400 mb-1" />
                Click "Run AI Review" to extract methodological gaps and calculate alignment score.
              </div>
            )}
          </div>

          {/* Target Publications */}
          <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-2xs">
            <div className="flex items-center justify-between mb-3 pb-2 border-b border-slate-100">
              <h3 className="text-sm font-bold text-slate-900 flex items-center gap-1.5">
                <BookOpen className="w-4 h-4 text-blue-600" />
                <span>Publications for Grounding ({prof.papers?.length || 0})</span>
              </h3>
              <button
                onClick={() => setShowPaperModal(true)}
                className="text-xs text-blue-600 font-bold hover:underline flex items-center gap-1"
              >
                <Plus className="w-3.5 h-3.5" />
                <span>Add Paper</span>
              </button>
            </div>

            {prof.papers?.length === 0 ? (
              <div className="text-center py-6 text-xs text-slate-400">
                No papers attached. Add papers so Gemini can cite real methodologies.
              </div>
            ) : (
              <div className="space-y-2.5 max-h-80 overflow-y-auto pr-1">
                {prof.papers.map((p) => (
                  <div key={p.id} className="p-3 rounded-xl bg-slate-50 border border-slate-200 text-xs">
                    <div className="font-bold text-slate-900 leading-snug">
                      {p.title}
                    </div>
                    <div className="text-[11px] text-slate-500 mt-1 flex items-center gap-2">
                      {p.year && <span>{p.year}</span>}
                      {p.venue && <span>• {p.venue}</span>}
                    </div>
                    {p.abstract && (
                      <p className="text-[11px] text-slate-600 line-clamp-2 mt-1.5 leading-relaxed">
                        {p.abstract}
                      </p>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Right Column: In-Page Email Composer (7 cols) */}
        <div className="lg:col-span-7">
          <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-2xs flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-4 pb-2 border-b border-slate-100">
                <div>
                  <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2">
                    <Mail className="w-4 h-4 text-blue-600" />
                    <span>Outreach & Follow-Up Email Drafter</span>
                  </h3>
                  <p className="text-xs text-slate-500">
                    Draft, refine, send, or copy-paste directly to your personal Gmail client
                  </p>
                </div>
              </div>

              {/* Quick AI Trigger Bar */}
              <div className="flex flex-wrap items-center gap-2 mb-3 bg-[#F8FAFC] p-2.5 rounded-xl border border-slate-200">
                <button
                  type="button"
                  onClick={handleGenerateDraft}
                  disabled={drafting}
                  className="px-3 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs shadow-2xs flex items-center gap-1.5 transition-all disabled:opacity-50"
                >
                  <Sparkles className="w-3.5 h-3.5" />
                  <span>{drafting ? "Generating..." : "✨ AI Initial Draft"}</span>
                </button>

                <button
                  type="button"
                  onClick={handleGenerateFollowUp}
                  disabled={drafting}
                  className="px-3 py-1.5 rounded-lg bg-amber-50 hover:bg-amber-100 border border-amber-300 text-amber-900 font-bold text-xs flex items-center gap-1.5 transition-all disabled:opacity-50"
                >
                  <RotateCw className="w-3.5 h-3.5 text-amber-600" />
                  <span>🔁 AI Follow-Up</span>
                </button>

                <div className="ml-auto flex items-center gap-2 text-xs">
                  <select
                    value={tone}
                    onChange={(e) => setTone(e.target.value)}
                    className="bg-white border border-slate-200 rounded-lg px-2 py-1 text-slate-700 font-semibold"
                  >
                    <option value="Formal Academic">Formal Academic</option>
                    <option value="Direct & Concise">Direct & Concise</option>
                    <option value="Technical Deep-Dive">Technical Deep-Dive</option>
                  </select>
                </div>
              </div>

              {/* Subject & Body Inputs */}
              <div className="space-y-2.5">
                <div>
                  <label className="block text-[11px] font-bold text-slate-700 mb-1">
                    Subject Line
                  </label>
                  <input
                    type="text"
                    value={subject}
                    onChange={(e) => setSubject(e.target.value)}
                    className="w-full px-3 py-2 text-xs bg-white border border-slate-200 rounded-xl font-bold text-slate-800"
                    placeholder="e.g. Prospective PhD Inquiry - Autonomous Agents - Sumit Raj"
                  />
                </div>

                <div>
                  <label className="block text-[11px] font-bold text-slate-700 mb-1">
                    Email Body
                  </label>
                  <textarea
                    rows={12}
                    value={body}
                    onChange={(e) => setBody(e.target.value)}
                    className="w-full p-3.5 text-xs bg-white border border-slate-200 rounded-xl font-sans text-slate-800 leading-relaxed placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Click 'AI Initial Draft' or 'AI Follow-Up' above, or compose manually..."
                  />
                </div>
              </div>
            </div>

            {/* Bottom Actions */}
            <div className="mt-4 pt-3 border-t border-slate-100 flex flex-wrap items-center justify-between gap-2">
              <div className="text-[11px] text-slate-500">
                Tip: Use <strong>"Copy for Gmail"</strong> to paste directly into your email client.
              </div>
              <div className="flex items-center gap-2">
                <button
                  onClick={handleCopyForGmail}
                  className={`px-3.5 py-2 rounded-xl border text-xs font-bold flex items-center gap-1.5 transition-all ${
                    copied
                      ? 'bg-emerald-50 border-emerald-300 text-emerald-800'
                      : 'bg-white hover:bg-slate-50 border-slate-200 text-slate-800 shadow-2xs'
                  }`}
                  title="Copy full message to paste into Gmail"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5 text-slate-600" />}
                  <span>{copied ? "Copied!" : "Copy for Gmail"}</span>
                </button>

                <button
                  onClick={handleSaveDraft}
                  className="px-3.5 py-2 rounded-xl bg-white hover:bg-slate-50 border border-slate-200 text-slate-700 text-xs font-bold shadow-2xs flex items-center gap-1.5"
                >
                  <Save className="w-3.5 h-3.5 text-slate-500" />
                  <span>Save Draft</span>
                </button>

                <button
                  onClick={handleSendNow}
                  className="px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold shadow-sm flex items-center gap-1.5"
                >
                  <Send className="w-3.5 h-3.5" />
                  <span>Send to Professor</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Add Paper Modal */}
      {showPaperModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-xs p-4">
          <div className="bg-white rounded-3xl max-w-md w-full p-6 border border-slate-200 shadow-2xl">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-sm font-bold text-slate-900">Attach Paper to Dossier</h3>
              <button onClick={() => setShowPaperModal(false)}>
                <X className="w-4 h-4 text-slate-400" />
              </button>
            </div>
            <form onSubmit={handleAddPaper} className="space-y-3 text-xs">
              <div>
                <label className="block text-slate-700 font-semibold mb-1">Paper Title *</label>
                <input
                  type="text"
                  required
                  value={newPaper.title}
                  onChange={(e) => setNewPaper({ ...newPaper, title: e.target.value })}
                  className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl"
                  placeholder="e.g. Attention Is All You Need"
                />
              </div>
              <div className="grid grid-cols-2 gap-2">
                <div>
                  <label className="block text-slate-700 font-semibold mb-1">Year</label>
                  <input
                    type="number"
                    value={newPaper.year}
                    onChange={(e) => setNewPaper({ ...newPaper, year: parseInt(e.target.value) })}
                    className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl"
                  />
                </div>
                <div>
                  <label className="block text-slate-700 font-semibold mb-1">Venue</label>
                  <input
                    type="text"
                    value={newPaper.venue}
                    onChange={(e) => setNewPaper({ ...newPaper, venue: e.target.value })}
                    className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl"
                    placeholder="NeurIPS / ICML"
                  />
                </div>
              </div>
              <div>
                <label className="block text-slate-700 font-semibold mb-1">Abstract</label>
                <textarea
                  rows={4}
                  value={newPaper.abstract}
                  onChange={(e) => setNewPaper({ ...newPaper, abstract: e.target.value })}
                  className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl"
                  placeholder="Paste abstract..."
                />
              </div>
              <div className="flex justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setShowPaperModal(false)}
                  className="px-3 py-1.5 rounded-xl bg-slate-100 text-slate-700 font-semibold"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-1.5 rounded-xl bg-blue-600 text-white font-bold"
                >
                  Save Paper
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default ProfessorDetailPage;
