import React, { useState, useEffect } from 'react';
import { useCompose } from '../../context/ComposeContext';
import { 
  X, 
  Minus, 
  Maximize2, 
  Minimize2, 
  Send, 
  Sparkles, 
  Copy, 
  Save, 
  Trash2, 
  RotateCw, 
  FileText,
  Check,
  ChevronDown
} from 'lucide-react';
import api from '../../services/api';
import toast from 'react-hot-toast';

const GmailCompose = () => {
  const { 
    isOpen, 
    isMinimized, 
    isMaximized, 
    composeData, 
    closeCompose, 
    toggleMinimize, 
    toggleMaximize,
    setComposeData
  } = useCompose();

  const [to, setTo] = useState('');
  const [subject, setSubject] = useState('');
  const [body, setBody] = useState('');
  const [professors, setProfessors] = useState([]);
  const [selectedProfId, setSelectedProfId] = useState(null);
  const [tone, setTone] = useState('Formal Academic');
  const [wordCount, setWordCount] = useState(250);
  const [followUpStage, setFollowUpStage] = useState(1);
  const [customHook, setCustomHook] = useState('');
  const [templates, setTemplates] = useState([]);
  
  const [isAiGenerating, setIsAiGenerating] = useState(false);
  const [isSending, setIsSending] = useState(false);
  const [copied, setCopied] = useState(false);

  // Load professors and templates
  useEffect(() => {
    const loadMetadata = async () => {
      try {
        const [profRes, tplRes] = await Promise.all([
          api.get('/professors'),
          api.get('/emails/templates')
        ]);
        setProfessors(profRes.data || []);
        setTemplates(tplRes.data || []);
      } catch (err) {
        console.error("Error loading compose metadata:", err);
      }
    };
    if (isOpen) {
      loadMetadata();
    }
  }, [isOpen]);

  // Sync state when composeData changes
  useEffect(() => {
    if (isOpen) {
      setTo(composeData.recipientEmail || '');
      setSubject(composeData.subject || '');
      setBody(composeData.body || '');
      setSelectedProfId(composeData.professorId || null);
      setFollowUpStage(composeData.followUpStage || 1);
      setCopied(false);
    }
  }, [isOpen, composeData]);

  if (!isOpen) return null;

  const handleSelectProfessor = (profId) => {
    setSelectedProfId(profId);
    const p = professors.find(x => x.id === parseInt(profId));
    if (p) {
      setTo(p.email);
      if (!subject) {
        setSubject(`Inquiry regarding PhD Openings in ${p.research_topics?.split(',')[0] || 'AI'}`);
      }
      setComposeData(prev => ({ ...prev, professorId: p.id, professorName: p.name, recipientEmail: p.email }));
    }
  };

  const handleGenerateInitialDraft = async () => {
    if (!selectedProfId) {
      toast.error("Please select a target professor first.");
      return;
    }
    setIsAiGenerating(true);
    try {
      const res = await api.post('/ai/draft-email', {
        professor_id: parseInt(selectedProfId),
        tone,
        word_count: wordCount
      });
      setSubject(res.data.subject);
      setBody(res.data.body);
      toast.success("Academic cold email drafted by Gemini!");
    } catch (err) {
      console.error(err);
      toast.error("Failed to generate draft with Gemini.");
    } finally {
      setIsAiGenerating(false);
    }
  };

  const handleGenerateFollowUp = async (stageNum = 1) => {
    if (!selectedProfId) {
      toast.error("Please select a target professor first.");
      return;
    }
    setIsAiGenerating(true);
    try {
      const res = await api.post('/ai/follow-up', {
        professor_id: parseInt(selectedProfId),
        follow_up_stage: stageNum,
        custom_hook: customHook || undefined
      });
      setSubject(res.data.subject);
      setBody(res.data.body);
      setFollowUpStage(stageNum);
      toast.success(`Follow-up (Stage ${stageNum}) generated by Gemini!`);
    } catch (err) {
      console.error(err);
      toast.error("Failed to generate follow-up.");
    } finally {
      setIsAiGenerating(false);
    }
  };

  const handleApplyTemplate = (tpl) => {
    const prof = professors.find(p => p.id === parseInt(selectedProfId)) || {};
    let sub = tpl.subject_template
      .replace('{{research_topic}}', prof.research_topics || 'AI Research')
      .replace('{{candidate_name}}', 'Sumit Raj');
    let b = tpl.body_template
      .replace('{{professor_last_name}}', prof.name ? prof.name.split(' ').pop() : 'Professor')
      .replace('{{candidate_name}}', 'Sumit Raj')
      .replace('{{candidate_degree}}', 'M.S. in Computer Science')
      .replace('{{candidate_field}}', 'Computer Science & AI')
      .replace('{{research_topic}}', prof.research_topics || 'AI Research')
      .replace('{{institution}}', prof.institution || 'your department');

    setSubject(sub);
    setBody(b);
    toast.success(`Applied template: "${tpl.name}"`);
  };

  const handleCopyToClipboard = () => {
    if (!body) {
      toast.error("Email body is empty.");
      return;
    }
    const fullText = `Subject: ${subject}\n\n${body}`;
    navigator.clipboard.writeText(fullText);
    setCopied(true);
    toast.success("Copied to clipboard! Ready to paste into your Gmail/Email client.", {
      icon: '📋',
      duration: 4000
    });
    setTimeout(() => setCopied(false), 3000);
  };

  const handleSaveDraft = async () => {
    if (!selectedProfId && !to) {
      toast.error("Please select or specify a recipient professor.");
      return;
    }
    try {
      const profId = selectedProfId || professors[0]?.id;
      await api.post('/emails', {
        professor_id: profId,
        subject: subject || 'Untitled PhD Outreach Draft',
        body: body || ''
      });
      toast.success("Draft saved to CRM!");
    } catch (err) {
      toast.error("Failed to save draft.");
    }
  };

  const handleSendEmail = async () => {
    if (!to || !body) {
      toast.error("Please specify recipient and message body.");
      return;
    }
    setIsSending(true);
    try {
      const profId = selectedProfId || professors[0]?.id;
      // 1. Save draft
      const draftRes = await api.post('/emails', {
        professor_id: profId,
        subject: subject || 'PhD Inquiry',
        body: body
      });
      const draftId = draftRes.data.id;

      // 2. Send
      const sendRes = await api.post('/emails/send', {
        draft_id: draftId,
        send_now: true
      });
      toast.success(sendRes.data.message || `Email dispatched to ${to}!`);
      closeCompose();
    } catch (err) {
      console.error(err);
      toast.error(err.response?.data?.detail || "Send failed. (You can also use 'Copy' to send from your own mail client).");
    } finally {
      setIsSending(false);
    }
  };

  return (
    <div 
      className={`fixed z-50 bg-white border border-slate-300 rounded-t-2xl shadow-2xl transition-all duration-200 flex flex-col ${
        isMaximized 
          ? 'inset-8 w-auto h-auto rounded-2xl' 
          : isMinimized 
            ? 'bottom-0 right-10 w-72 h-11' 
            : 'bottom-0 right-10 w-[620px] h-[640px]'
      }`}
    >
      {/* Gmail Window Header */}
      <div className="bg-[#F2F6FC] px-4 py-2.5 rounded-t-2xl flex items-center justify-between border-b border-slate-200 select-none">
        <div className="flex items-center gap-2">
          <div className="w-2.5 h-2.5 rounded-full bg-blue-600"></div>
          <span className="text-xs font-bold text-slate-800">
            {composeData.mode === 'follow_up' 
              ? `Follow-Up Inquiry (${composeData.professorName || 'Professor'})` 
              : 'New Outreach Message'}
          </span>
        </div>

        <div className="flex items-center gap-1 text-slate-500">
          <button 
            onClick={toggleMinimize} 
            className="p-1 hover:bg-slate-200 rounded-md transition-colors"
            title={isMinimized ? "Expand" : "Minimize"}
          >
            <Minus className="w-3.5 h-3.5" />
          </button>
          <button 
            onClick={toggleMaximize} 
            className="p-1 hover:bg-slate-200 rounded-md transition-colors"
            title={isMaximized ? "Restore size" : "Maximize"}
          >
            {isMaximized ? <Minimize2 className="w-3.5 h-3.5" /> : <Maximize2 className="w-3.5 h-3.5" />}
          </button>
          <button 
            onClick={closeCompose} 
            className="p-1 hover:bg-slate-200 hover:text-rose-600 rounded-md transition-colors"
            title="Close"
          >
            <X className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      {!isMinimized && (
        <div className="flex-1 flex flex-col overflow-hidden bg-white">
          {/* Recipient & Professor Selector */}
          <div className="px-4 py-2 border-b border-slate-100 flex items-center gap-2 text-xs">
            <span className="text-slate-500 w-12 shrink-0 font-medium">To:</span>
            <input
              type="email"
              value={to}
              onChange={(e) => setTo(e.target.value)}
              placeholder="Professor email address..."
              className="flex-1 focus:outline-none text-slate-800 font-medium"
            />
            {professors.length > 0 && (
              <select
                value={selectedProfId || ''}
                onChange={(e) => handleSelectProfessor(e.target.value)}
                className="text-[11px] bg-slate-50 hover:bg-slate-100 border border-slate-200 rounded-lg px-2 py-1 text-slate-700 font-medium max-w-[200px] truncate"
              >
                <option value="">Select target faculty...</option>
                {professors.map(p => (
                  <option key={p.id} value={p.id}>
                    {p.name} ({p.institution})
                  </option>
                ))}
              </select>
            )}
          </div>

          {/* Subject Line */}
          <div className="px-4 py-2 border-b border-slate-100 flex items-center gap-2 text-xs">
            <span className="text-slate-500 w-12 shrink-0 font-medium">Subject:</span>
            <input
              type="text"
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              placeholder="Academic inquiry subject line..."
              className="flex-1 focus:outline-none text-slate-800 font-semibold"
            />
          </div>

          {/* AI Co-Pilot & Template Action Strip */}
          <div className="bg-[#FAFBFD] px-4 py-2 border-b border-slate-200/80 flex flex-wrap items-center justify-between gap-2 text-xs">
            <div className="flex items-center gap-1.5">
              <button
                type="button"
                onClick={handleGenerateInitialDraft}
                disabled={isAiGenerating}
                className="px-2.5 py-1 rounded-lg bg-indigo-50 hover:bg-indigo-100 border border-indigo-200 text-indigo-700 text-[11px] font-semibold flex items-center gap-1 transition-all disabled:opacity-50"
                title="Synthesize papers and draft cold email"
              >
                <Sparkles className="w-3 h-3 text-indigo-600" />
                <span>{isAiGenerating ? "Generating..." : "✨ AI Initial Draft"}</span>
              </button>

              <div className="relative group">
                <button
                  type="button"
                  onClick={() => handleGenerateFollowUp(1)}
                  disabled={isAiGenerating}
                  className="px-2.5 py-1 rounded-lg bg-amber-50 hover:bg-amber-100 border border-amber-200 text-amber-800 text-[11px] font-semibold flex items-center gap-1 transition-all disabled:opacity-50"
                >
                  <RotateCw className="w-3 h-3 text-amber-600" />
                  <span>🔁 AI Follow-Up</span>
                </button>
              </div>

              {templates.length > 0 && (
                <select
                  onChange={(e) => {
                    const tpl = templates.find(t => t.id === parseInt(e.target.value));
                    if (tpl) handleApplyTemplate(tpl);
                  }}
                  defaultValue=""
                  className="text-[11px] bg-white border border-slate-200 rounded-lg px-2 py-1 text-slate-600 font-medium"
                >
                  <option value="" disabled>Insert Template...</option>
                  {templates.map(t => (
                    <option key={t.id} value={t.id}>{t.name}</option>
                  ))}
                </select>
              )}
            </div>

            <div className="flex items-center gap-2 text-[11px] text-slate-500">
              <select
                value={tone}
                onChange={(e) => setTone(e.target.value)}
                className="bg-transparent border-0 text-slate-600 font-medium focus:outline-none cursor-pointer"
              >
                <option value="Formal Academic">Formal Academic</option>
                <option value="Direct & Concise">Direct & Concise</option>
                <option value="Technical Deep-Dive">Technical Focus</option>
              </select>
            </div>
          </div>

          {/* Email Body Editor */}
          <div className="flex-1 p-4 overflow-y-auto">
            <textarea
              value={body}
              onChange={(e) => setBody(e.target.value)}
              placeholder="Write your email to the professor or click '✨ AI Initial Draft' / '🔁 AI Follow-Up' above to generate grounded academic outreach..."
              className="w-full h-full resize-none focus:outline-none text-slate-800 font-sans text-xs leading-relaxed placeholder:text-slate-400"
            />
          </div>

          {/* Gmail Bottom Action Bar */}
          <div className="px-4 py-3 bg-[#F6F8FC] border-t border-slate-200 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={handleSendEmail}
                disabled={isSending}
                className="px-5 py-2 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs shadow-md shadow-blue-600/20 flex items-center gap-1.5 transition-all disabled:opacity-50"
              >
                <Send className="w-3.5 h-3.5" />
                <span>{isSending ? "Sending..." : "Send"}</span>
              </button>

              <button
                type="button"
                onClick={handleCopyToClipboard}
                className={`px-3 py-2 rounded-xl border text-xs font-semibold flex items-center gap-1.5 transition-all ${
                  copied 
                    ? 'bg-emerald-50 border-emerald-300 text-emerald-700' 
                    : 'bg-white hover:bg-slate-100 border-slate-200 text-slate-700 shadow-2xs'
                }`}
                title="Copy full email (Subject + Body) to clipboard to paste into Gmail"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5 text-slate-600" />}
                <span>{copied ? "Copied!" : "Copy for Gmail"}</span>
              </button>

              <button
                type="button"
                onClick={handleSaveDraft}
                className="px-3 py-2 rounded-xl bg-white hover:bg-slate-100 border border-slate-200 text-slate-700 text-xs font-semibold flex items-center gap-1.5 shadow-2xs transition-all"
                title="Save draft in CRM outbox"
              >
                <Save className="w-3.5 h-3.5 text-slate-500" />
                <span>Save Draft</span>
              </button>
            </div>

            <button
              type="button"
              onClick={() => {
                if (window.confirm("Discard this email?")) {
                  setBody('');
                  setSubject('');
                  closeCompose();
                }
              }}
              className="p-2 text-slate-400 hover:text-rose-600 hover:bg-slate-100 rounded-lg transition-colors"
              title="Discard draft"
            >
              <Trash2 className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default GmailCompose;
